services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app:cached
    command: sh -c 'trap "exit 0" TERM; tail -f /dev/null & wait'

  nats-1:
    image: nats
    command: -c /etc/server.conf --name nats-1 -p 4222 -m 8222
    volumes:
      - ./docker/nats/server.conf:/etc/server.conf
    ports:
      - "4222:4222"
      - "8222:8222"

  nats-2:
    image: nats
    command: -c /etc/server.conf --name nats-2 -p 4222 -m 8222
    volumes:
      - ./docker/nats/server.conf:/etc/server.conf
    ports:
      - "4223:4222"

  nats-3:
    image: nats
    command: -c /etc/server.conf --name nats-3 -p 4222 -m 8222
    volumes:
      - ./docker/nats/server.conf:/etc/server.conf
    ports:
      - "4224:4222"
