<?php

declare(strict_types=1);

namespace Thesis\Nats\Internal\Protocol;

/**
 * @internal
 */
final class Sub
{
    /**
     * @param non-empty-string $subject the subject name to subscribe to
     * @param non-empty-string $sid a unique alphanumeric subscription ID, generated by the client
     * @param ?non-empty-string $queueGroup if specified, the subscriber will join this queue group
     */
    public function __construct(
        public readonly string $subject,
        public readonly string $sid,
        public readonly ?string $queueGroup = null,
    ) {}
}
