on:
  workflow_dispatch: ~
  push:
    branches: ['main', '*.*.x']
  pull_request: ~

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      nats-1:
        image: nats
        options: -c /etc/server.conf --name nats-1 -p 4222 -m 8222
        volumes:
          - ./nats/server.conf:/etc/server.conf
        ports:
          - "4222:4222"
          - "8222:8222"
      nats-2:
        image: nats
        options: -c /etc/server.conf --name nats-2 -p 4222 -m 8222
        volumes:
          - ./nats/server.conf:/etc/server.conf
        ports:
          - "4223:4222"
      nats-3:
        image: nats
        options: -c /etc/server.conf --name nats-3 -p 4222 -m 8222
        volumes:
          - ./nats/server.conf:/etc/server.conf
        ports:
          - "4224:4222"
    strategy:
      matrix:
        php: ["8.3", "8.4"]
        dependencies: ["locked", "lowest", "highest"]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-file: development
          tools: composer:v2
          extensions: pcntl
          ini-values: disable_functions=pcntl_fork
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
          dependency-versions: ${{ matrix.dependencies }}
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH || '{}' }}
      - run: composer test -- --colors=always
